CREATE TABLE companies (
  company_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(32) NOT NULL,
  bank_account_number VARCHAR(12)
);

CREATE TABLE raw_materials (
  material_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  material_name VARCHAR(16) UNIQUE NOT NULL,
  price_per_kg NUMERIC(10,2)
);

CREATE TABLE supplies (
  supply_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id INT NOT NULL,
  received_at TIMESTAMPTZ NOT NULL,
  processed_at TIMESTAMPTZ
);

-- CREATE TABLE materials (
--   material_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   material_name VARCHAR(8) UNIQUE NOT NULL
-- );

-- CREATE TABLE machine_statuses (
--   status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   status VARCHAR(8) NOT NULL
-- );

CREATE TYPE machine_status AS ENUM ('WORKING', 'BROKEN');

CREATE TABLE machine_ratios (
  ratio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  material_id INT NOT NULL,
  ratio INT NOT NULL,
  machine_id INT NOT NULL
);

CREATE TABLE machines (
  machine_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  status machine_status NOT NULL DEFAULT 'WORKING',
  purchase_price FLOAT NOT NULL,
  purchased_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE machine_orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  supplier_id INT NOT NULL,
  ordered_at TIMESTAMPTZ NOT NULL,
  received_at TIMESTAMPTZ
);

CREATE TABLE material_suppliers (
  supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  supplier_name VARCHAR(16) NOT NULL
);

CREATE TABLE material_orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  supplier_id INT NOT NULL,
  ordered_at TIMESTAMPTZ NOT NULL,
  received_at TIMESTAMPTZ
);

CREATE TABLE material_order_items (
  item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  material_id INT NOT NULL,
  amount INT NOT NULL,
  order_id INT NOT NULL
);

CREATE TABLE phone_manufacturers (
  manufacturer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  manufacturer_name VARCHAR(8) NOT NULL
);

CREATE TABLE electronics (
  electronic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  produced_at TIMESTAMPTZ NOT NULL,
  sold_at TIMESTAMPTZ
);

CREATE TABLE electronics_orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  manufacturer_id INT NOT NULL,
  amount INT NOT NULL,
  ordered_at TIMESTAMPTZ NOT NULL,
  processed_at TIMESTAMPTZ
);
 
CREATE TABLE lookup_values (
  value_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  electronics_price FLOAT NOT NULL
);

CREATE TABLE bank_details (
  bank_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  company_name VARCHAR(32) NOT NULL UNIQUE,
  bank_number
)

ALTER TABLE supplies ADD FOREIGN KEY (material_id) REFERENCES materials (material_id);

ALTER TABLE machine_ratios ADD FOREIGN KEY (material_id) REFERENCES materials (material_id);

ALTER TABLE machine_ratios ADD FOREIGN KEY (machine_id) REFERENCES machines (machine_id);

-- ALTER TABLE machines ADD FOREIGN KEY (status_id) REFERENCES machine_statuses (status_id);

ALTER TABLE material_orders ADD FOREIGN KEY (supplier_id) REFERENCES material_suppliers (supplier_id);

ALTER TABLE material_order_items ADD FOREIGN KEY (material_id) REFERENCES materials (material_id);

ALTER TABLE material_order_items ADD FOREIGN KEY (order_id) REFERENCES material_orders (order_id);

ALTER TABLE electronics_orders ADD FOREIGN KEY (manufacturer_id) REFERENCES phone_manufacturers (manufacturer_id);
