CREATE TABLE companies (
  company_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(32) NOT NULL,
  bank_account_number VARCHAR(12)
);

CREATE TYPE order_status AS ENUM (
  'PENDING',
  'ACCEPTED',
  'REJECTED',
  'IN_PROGRESS',
  'COMPLETED',
  'IN_TRANSIT',
  'DISASTER'
);

CREATE TABLE raw_materials (
  material_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  material_name VARCHAR(16) UNIQUE NOT NULL,
  price_per_kg NUMERIC(10,2)
);

CREATE TABLE material_orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  supplier_id INT NOT NULL,
  external_order_id INT,
  status order_status NOT NULL DEFAULT 'PENDING',
  placed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  received_at TIMESTAMPTZ
);

CREATE TABLE material_order_items (
  item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  material_id INT NOT NULL,
  quantity_kg INT NOT NULL,
  price_per_kg NUMERIC(10,2) NOT NULL,
  order_id INT NOT NULL
);

CREATE TABLE material_supplies (
  supply_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  material_id INT NOT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE machine_orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  supplier_id INT NOT NULL,
  external_order_id INT,
  status order_status NOT NULL DEFAULT 'PENDING',
  placed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  received_at TIMESTAMPTZ
);

CREATE TABLE machines (
  machine_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  output_amount INT NOT NULL,
  status machine_status NOT NULL DEFAULT 'STANDBY',
  purchase_price FLOAT NOT NULL,
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  received_at TIMESTAMPTZ,
  removed_at TIMESTAMPTZ,
  order_id INT NOT NULL
);

CREATE TABLE machine_statuses (
  status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(8) NOT NULL
);

CREATE TABLE machine_ratios (
  ratio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  material_id INT NOT NULL,
  ratio INT NOT NULL,
  machine_id INT NOT NULL
);



-- CREATE TABLE materials (
--   material_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   material_name VARCHAR(8) UNIQUE NOT NULL
-- );

-- CREATE TABLE machine_statuses (
--   status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   status VARCHAR(8) NOT NULL
-- );

-- CREATE TABLE machine_orders (
--   order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   supplier_id INT NOT NULL,
--   ordered_at TIMESTAMPTZ NOT NULL,
--   received_at TIMESTAMPTZ
-- );

-- CREATE TABLE material_suppliers (
--   supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   supplier_name VARCHAR(16) NOT NULL
-- );

-- CREATE TABLE material_orders (
--   order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   supplier_id INT NOT NULL,
--   ordered_at TIMESTAMPTZ NOT NULL,
--   received_at TIMESTAMPTZ
-- );

-- CREATE TABLE material_order_items (
--   item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   material_id INT NOT NULL,
--   amount INT NOT NULL,
--   order_id INT NOT NULL
-- );

-- CREATE TABLE phone_manufacturers (
--   manufacturer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   manufacturer_name VARCHAR(8) NOT NULL
-- );

CREATE TABLE electronics (
  electronic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  produced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sold_at TIMESTAMPTZ
);

CREATE TABLE electronics_orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  manufacturer_id INT NOT NULL,
  amount INT NOT NULL,
  status order_status NOT NULL DEFAULT 'PENDING',
  ordered_at TIMESTAMPTZ NOT NULL,
  processed_at TIMESTAMPTZ
);
 
CREATE TABLE lookup_values (
  value_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  electronics_price_per_unit NUMERIC(10,2) NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- CREATE TABLE bank_details (
--   bank_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
--   company_name VARCHAR(32) NOT NULL UNIQUE,
--   bank_number
-- )

ALTER TABLE material_supplies ADD FOREIGN KEY (material_id) REFERENCES raw_materials (material_id);

ALTER TABLE machine_ratios ADD FOREIGN KEY (material_id) REFERENCES raw_materials (material_id);

ALTER TABLE machine_ratios ADD FOREIGN KEY (machine_id) REFERENCES machines (machine_id);

ALTER TABLE machines ADD FOREIGN KEY (status_id) REFERENCES machine_statuses (status_id);

ALTER TABLE material_orders ADD FOREIGN KEY (supplier_id) REFERENCES companies (company_id);

ALTER TABLE material_order_items ADD FOREIGN KEY (material_id) REFERENCES raw_materials (material_id);

ALTER TABLE material_order_items ADD FOREIGN KEY (order_id) REFERENCES material_orders (order_id);

ALTER TABLE electronics_orders ADD FOREIGN KEY (manufacturer_id) REFERENCES companies (company_id);